name: Automatic branch deletion after closing dead domains PR

on:
  pull_request:
      types:
      - closed

jobs:
  delete-branch:
    # Only run if PR title starts with 'Automated dead domains fix'
    if: startsWith(github.event.pull_request.title, 'Automated dead domains fix')
    name: Automated branch deletion
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = context.payload.pull_request.head.ref;

            if (branchName.startsWith('fix/dead-domains-')) {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${branchName}`,
              });

              core.info(`Deleted branch ${branchName}`);
            } else {
              core.info(`Branch ${branchName} is not an automated fix branch. Skipping deletion.`);
            }
